(TeX-add-style-hook "main"
 (lambda ()
    (LaTeX-add-bibliographies
     "bibfiles.bib")
    (LaTeX-add-environments
     "lemma"
     "corollary")
    (LaTeX-add-labels
     "sec:Theory"
     "eq:conduit"
     "eq:GP"
     "eq:scaling1"
     "eq:GPscaled"
     "eq:IBE"
     "eq:raresoln"
     "eq:coordSub1"
     "eq:BCDSW"
     "fig:rare_wave_inv"
     "eq:ND"
     "eq:FlowRateProfile"
     "fig:chars1"
     "fig:chars2"
     "sec:Exp"
     "fig:expsys"
     "fig:af"
     "sec:Dis"
     "sec:Con")
    (TeX-add-symbols
     '("DA" 1)
     '("MM" 1)
     "eps"
     "ifl"
     "efl"
     "iande")
    (TeX-run-style-hooks
     "ulem"
     "normalem"
     "cancel"
     "subfigure"
     "float"
     "bm"
     "natbib"
     "setspace"
     "appendix"
     "titletoc"
     "toc"
     "title"
     "wasysym"
     "pgfplots"
     "hyperref"
     "siunitx"
     "amssymb"
     "amsmath"
     "xcolor"
     "dvipsnames"
     "color"
     "graphicx"
     "latex2e"
     "jfm10"
     "jfm")))

